# Generated by Django 2.2 on 2021-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20210327_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='is_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestdata',
            name='result',
            field=models.TextField(default=''),
        ),
    ]
