# Generated by Django 2.2 on 2021-04-24 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20210328_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.TextField()),
                ('access_token', models.CharField(max_length=255)),
                ('shots', models.PositiveIntegerField()),
                ('no_qubits', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_fetched', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestData',
        ),
    ]
