# Generated by Django 2.2 on 2021-04-26 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='shots',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200)]),
        ),
    ]
