# Generated by Django 2.2 on 2021-04-26 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20210426_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='no_qubits',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
