# Generated by Django 2.2 on 2021-05-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_auto_20210427_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='results',
        ),
        migrations.AlterField(
            model_name='result',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles_api.Job'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
