# Generated by Django 2.2 on 2021-05-17 14:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20210502_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='job',
        ),
        migrations.AddField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 17, 14, 46, 12, 308916, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='is_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='results',
            field=models.TextField(default=datetime.datetime(2021, 5, 17, 14, 46, 24, 740773, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
