# Generated by Django 2.2 on 2021-05-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_auto_20210517_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='is_fetched',
        ),
        migrations.AddField(
            model_name='result',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Job'),
        ),
    ]
