# Generated by Django 2.2 on 2021-05-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_singlequbitgate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experiment',
        ),
        migrations.AddField(
            model_name='singlequbitgate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Job'),
        ),
        migrations.AlterField(
            model_name='singlequbitgate',
            name='params',
            field=models.TextField(null=True),
        ),
    ]
