# Generated by Django 2.2 on 2021-05-24 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_auto_20210524_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlequbitgate',
            name='qubits',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7)]),
        ),
    ]
