# Generated by Django 2.2 on 2021-11-15 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clusterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfQubits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('graphState', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComputeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterState', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdl_rest_api.clusterState')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experimentName', models.CharField(max_length=255)),
                ('projectId', models.CharField(max_length=255)),
                ('maxRuntime', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('ComputeSettings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdl_rest_api.ComputeSettings')),
            ],
        ),
        migrations.CreateModel(
            name='qubitComputing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitConfiguration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experimentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cdl_rest_api.ExperimentBase')),
                ('experimentId', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('cdl_rest_api.experimentbase',),
        ),
        migrations.CreateModel(
            name='QubitMeasurementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encodedQubitIndex', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('theta', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('phi', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('ComputeSettings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encodedQubitMeasurements', to='cdl_rest_api.ComputeSettings')),
            ],
        ),
        migrations.AddField(
            model_name='computesettings',
            name='qubitComputing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdl_rest_api.qubitComputing'),
        ),
        migrations.CreateModel(
            name='CircuitConfigurationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitAngleName', models.CharField(max_length=255)),
                ('circuitAngleValue', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('qubitComputing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuitAngles', to='cdl_rest_api.qubitComputing')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('totalCounts', models.PositiveIntegerField()),
                ('numberOfDetectors', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('singlePhotonRate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalTime', models.PositiveIntegerField()),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdl_rest_api.Experiment')),
            ],
        ),
    ]
